name: flutter_advanced_app
description: "A new Flutter project."

publish_to: "none" # Prevent publishing this app to pub.dev (private project)

version: 1.0.0+1 # App version (major.minor.patch+build)

environment:
  sdk: ^3.5.4 # Required Dart SDK version

dependencies:
  flutter:
    sdk: flutter # Core Flutter framework
  cupertino_icons: ^1.0.8 # Icons for iOS-styled apps
  dio: ^5.7.0 # HTTP client for API requests
  flutter_bloc: ^8.1.6 # Simplifies state management using BLoC
  freezed: ^2.5.7 # Generates immutable data classes
  freezed_annotation: ^2.4.4 # Annotations used with `freezed`
  get_it: ^8.0.2 # Service locator for dependency injection
  json_annotation: ^4.9.0 # Helps annotate JSON models
  json_serializable: ^6.9.0 # Generates JSON serialization logic

dev_dependencies:
  flutter_lints: ^5.0.0 # Enforces coding best practices
  flutter_test:
    sdk: flutter # Tools for writing and running tests

flutter:
  uses-material-design: true # Enable Material Icons in the app
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
