default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firbase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:250902365135:android:e0bd3490b2aa6e6f5088ba",
      firebase_cli_token: "1//03w-kjM_wNQp1CgYIARAAGAMSNwF-L9Ir2vsyYfjv39kLQNNhSIadFkYSWrx5sRX3RzrBloSxjS6rtvj6rcZcYw1rTX1uvdxunng",
      android_artifact_type: "APK",
      apk_path:	"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ma7m0o0od.adel@gmail.com, hana2helmi@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution Release"
    )
  end
end
